export const types={
    SEND_REQUEST:'SEND_REQUEST',
    SEND_REQUEST_SUCCESS:'SEND_REQUEST_SUCCESS',
    SEND_REQUEST_FAILURE:'SEND_REQUEST_FAILURE',

    SEND_REQUEST_DELETE_SUCCESS:'SEND_REQUEST_DELETE_SUCCESS',

    ADD_USER_REQUEST:'ADD_USER_REQUEST',
    ADD_USER_SUCCESS:'ADD_USER_SUCCESS',
    ADD_USER_FAILURE:'ADD_USER_FAILURE',

    SEND_REQUEST_EDIT:'SEND_REQUEST_EDIT',
    GET_USER_DATA_FOR_UPDATION:'GET_USER_DATA_FOR_UPDATION',
    SEND_REQUEST_EDIT_SUCCESS:'SEND_REQUEST_EDIT_SUCCESS',
    SEND_REQUEST_EDIT_FAILURE:'SEND_REQUEST_EDIT_FAILURE',
}
